API/urls.py
# Importaciones del programa
from . import views

# Django
from django.urls import path, include

# Rest Framework
from rest_framework import routers

router = routers.DefaultRouter()

router.register('comments', views.CommentsViewSet)
router.register('stars', views.StarsViewSet)
router.register('product', views.ProductViewSet)
router.register('problems', views.ProblemsViewSet)
router.register('problems_tikets', views.Problems_TiketsViewSet)
router.register('client', views.ClientViewSet)
router.register('certificate', views.CertificateViewSet)
router.register('tecnic', views.TecnicViewSet)
router.register('manager', views.ManagerViewSet)
router.register('callcenter', views.CallCenterViewSet)
router.register('user', views.UserViewSet)
router.register('notifications', views.PushNotificationAPIView, basename='notifications')

urlpatterns = [
    path('', include(router.urls)),
]

WorkSniffs/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # Vistas normales
    path('', include("startapp.urls")),
    path('manager/', include("manager.urls")),
    path('callcenter/', include("callcenter.urls")),
    path('tecnic/', include("tecnic.urls")),
    path('user/', include("user.urls")),

    # API y documentación
    path('api/', include("API.urls")),
    path('docs/', include_docs_urls(title='WorkSniffs API', public=True)),
]

# Añadimos las rutas de los archivos multimedia
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

callcenter/urls.py
from django.urls import path
from . import views

app_name = "callcenter"

urlpatterns = [
    path('', views.index, name='index'),
    path('create_client/', views.create_client, name='create_client'),
    path('update_client/', views.update_client, name='update_client'),
    path('delete_client/<int:id>/', views.delete_client, name='delete_client'),
]

manager/urls.py
from django.urls import path
from . import views

app_name = "manager"

urlpatterns = [
    path("", views.principal_page, name="principal_page"),
    path("workers/", views.workers, name="workers"),
    path("delete_worker/<int:id>", views.delete_worker, name="delete_worker"),
    path("edit_worker/", views.edit_worker, name="edit_worker"),
    path("block_worker/<int:id>", views.block_worker, name="block_worker"),
    path("unblock_worker/<int:id>", views.unblock_worker, name="unblock_worker"),
    path("clients/", views.clients, name="clients"),
    path("accept_client/<int:id>", views.accept_client, name="accept_client"),
    path("reject_client/<int:id>", views.reject_client, name="reject_client"),
]

startapp/urls.py
from django.urls import path
from . import views

app_name = "startapp"

urlpatterns = [
    path("", views.login_view, name="login_view"),
    path("logout", views.logout_view, name="logout_view"),
    path("ticket/<str:type_user>/", views.ticket, name="ticket"),
]

tecnic/urls.py
from django.urls import path
from . import views

app_name = 'tecnic'

urlpatterns = [
    path('', views.intro, name='intro'),
    path('client/<int:id>', views.client, name='client'),
    path('change_status/<int:id>', views.change_status, name='change_status'),
    path('configuration', views.configuration, name='configuration'),
]

startapp/models.py
from django.db import models

# Create your models here.

startapp/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login, logout, authenticate
from API.models import Manger, CallCenter, Problems, Problems_Tikets, Tecnic, User

def login_view(request):
    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")

        # Obtener el usuario por su email
        user = User.objects.filter(email=email).first()

        if user is not None:
            # Autenticar con el campo username
            user = authenticate(request, username=user.username, password=password)
            print(user)

            if user is not None:
                login(request, user)

                # Buscar qué tipo de usuario es y redirigirlo a su página
                if Manger.objects.filter(user=user).exists():
                    return redirect("manager:principal_page")
                elif CallCenter.objects.filter(user=user).exists():
                    return redirect("callcenter:index")
                elif Tecnic.objects.filter(user=user).exists():
                    return redirect("tecnic:intro")
                else:
                    return render(request, "startapp/login_view.html", {"message": "Tipo de usuario no válido"})
            else:
                return render(request, "startapp/login_view.html", {"message": "Credenciales incorrectas"})
        else:
            return render(request, "startapp/login_view.html", {"message": "Usuario no encontrado"})
    else:
        return render(request, "startapp/login_view.html")

def logout_view(request):
    logout(request)
    return render(request, "startapp/login_view.html")

def ticket(request, type_user):
    if request.method == "POST":
        email = request.POST.get("email")
        type_problem = request.POST.get("type_problem")
        description = request.POST.get("description")
        photo = request.FILES.get("image")

        # Crear el ticket
        ticket = Problems_Tikets(
            description=description,
            problem=Problems.objects.get(pk=type_problem),
            user_with_problem=email,
            type_user=type_user,
            photo=photo
        )
        ticket.save()
        if (type_user == "tecnic"):
            return render(request, "ticket/ticket.html", {
                "type_user": type_user,
                "success": "Ticket enviado con éxito",
                "problems": Problems.objects.all(),
                "tecnic": Tecnic.objects.get(user=request.user)
            })
        else:
            return render(request, "ticket/ticket.html", {
                "type_user": type_user,
                "success": "Ticket enviado con éxito",
                "problems": Problems.objects.all(),
                "tecnic": None
            })
    else:
        if (type_user == "tecnic"):
            return render(request, "ticket/ticket.html", {
                "type_user": type_user,
                "problems": Problems.objects.all(),
                "tecnic": Tecnic.objects.get(user=request.user)
            })
        else:
            return render(request, "ticket/ticket.html", {
                "type_user": type_user,
                "problems": Problems.objects.all(),
                "tecnic": None
            })

startapp/templates/ticket/ticket.html
{% extends 'layout.html' %}
{% load static %}

{% block sidebar %}
{% if type_user == 'manager' %}
    <div class="select_item">
        <ul class="list_sidebar">
            <a href="{% url 'manager:principal_page' %}">
                <li class="item_sidebar">
                    Inicio
                </li>
            </a>
            <a href="{% url 'manager:workers' %}">
                <li class="item_sidebar">
                    Trabajadores
                </li>
            </a>
            <a href="{% url 'manager:clients' %}">
                <li class="item_sidebar">
                    Clientes
                </li>
            </a>
        </ul>
        <div class="ticket_sidebar">
            <a href="{% url 'startapp:ticket' 'manager' %}" style="color: blue; text-decoration: underline;">
                Ticket
            </a>
        </div>
    </div>
{% elif type_user == 'callcenter' %}
    <div class="select_item">
        <ul class="list_sidebar">
            <a href="{% url 'callcenter:index' %}">
                <li class="item_sidebar" style="color: blue; text-decoration: underline;">
                    Administrar clientes
                </li>
            </a>
            <a href="{% url 'callcenter:create_client' %}">
                <li class="item_sidebar">
                    Crear un pedido
                </li>
            </a>
        </ul>
        <div class="ticket_sidebar">
            <a href="{% url 'startapp:ticket' 'callcenter' %}" style="color: blue; text-decoration: underline;">
                Ticket
            </a>
        </div>
    </div>
{% elif type_user == 'tecnic' %}
    <div class="select_item">
        <ul class="list_sidebar">
            <a href="{% url 'tecnic:intro' %}">
                <li class="item_sidebar">
                    Inicio
                </li>
            </a>
            <a href="{% url 'tecnic:configuration' %}">
                <li class="item_sidebar">
                    Configuración
                </li>
            </a>
            <a href="{% url 'startapp:ticket' 'tecnic' %}">
                <li class="item_sidebar"  style="color: blue; text-decoration: underline;">
                    Ticket
                </li>
            </a>
            <li>Clientes</li>
            {% for client in  tecnic.clients.all %}
            <a href="{% url 'tecnic:client' client.id %}">
                <li class="item_sidebar">
                    {{ client.username }} - {{ client.identity }}
                </li>
            </a>
            {% endfor %}
        </ul>
    </div>
{% else %}
    <div class="select_item">
        <div class="ticket_sidebar">
            <a href="{% url 'startapp:ticket' 'client' %}" style="color: blue; text-decoration: underline;">
                Ticket
            </a>
        </div>
    </div>
{% endif %}
{% endblock %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
{% csrf_token %}
    <div class="container text-center body_form">
        <div class="row">
            <div class="col">
                <h3 class="principal_text">Crear Ticket</h3>
                <div class="container_create">
                    <div class="input_info">
                        <label for="email">Correo Electronico</label>
                        <input type="text" name="email" id="email" class="form-control" value="{{ user.email }}" required>
                    </div>

                    <div class="input_info">
                        <label for="type_problem">Selecciona el tipo de problema</label>
                        <select name="type_problem" id="type_problem" class="select_worker">
                            {% for problem in problems %}
                            <option value="{{ problem.id }}">
                                {{ problem.title_description }} - {{ problem.description }}
                            </option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="input_info">
                        <label for="description">Describa el problema</label>
                        <textarea name="description" id="description" cols="30" rows="10"></textarea>
                    </div>
                </div>
            </div>
            <div class="col">
                <h3 class="principal_text">Comprobantes</h3>
                <div class="container_create">
                    <div class="input_info">
                        <label for="image">Subir una foto del problema</label>
                        <input type="file" name="image" id="image" class="form-control" required onchange="previewImage(this)">

                        <div id="imagePreview">
                            <img id="preview" src="" alt="Vista previa de la imagen">
                        </div>
                    </div>
                    <div class="input_info">
                        <button type="submit" class="btn btn-success">Enviar Ticket</button>
                    </div>
                </div>
                {% if message %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
                {% endif %}

                {% if success %}
                <div class="alert alert-success" role="alert">
                    {{ success }}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</form>
{% endblock %}