API/urls.py
# Importaciones del programa
from . import views

# Django
from django.urls import path, include

# Rest Framework
from rest_framework import routers

router = routers.DefaultRouter()

router.register('comments', views.CommentsViewSet)
router.register('stars', views.StarsViewSet)
router.register('product', views.ProductViewSet)
router.register('problems', views.ProblemsViewSet)
router.register('problems_tikets', views.Problems_TiketsViewSet)
router.register('client', views.ClientViewSet)
router.register('certificate', views.CertificateViewSet)
router.register('tecnic', views.TecnicViewSet)
router.register('manager', views.ManagerViewSet)
router.register('callcenter', views.CallCenterViewSet)
router.register('user', views.UserViewSet)
router.register('notifications', views.PushNotificationAPIView, basename='notifications')

urlpatterns = [
    path('', include(router.urls)),
]

WorkSniffs/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # Vistas normales
    path('', include("startapp.urls")),
    path('manager/', include("manager.urls")),
    path('callcenter/', include("callcenter.urls")),
    path('tecnic/', include("tecnic.urls")),
    path('user/', include("user.urls")),

    # API y documentación
    path('api/', include("API.urls")),
    path('docs/', include_docs_urls(title='WorkSniffs API', public=True)),
]

# Añadimos las rutas de los archivos multimedia
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

startapp/urls.py
from django.urls import path
from . import views

app_name = "startapp"

urlpatterns = [
    path("", views.login_view, name="login_view"),
    path("logout", views.logout_view, name="logout_view"),
    path("ticket/<str:type_user>/", views.ticket, name="ticket"),
]

tecnic/urls.py
from django.urls import path
from . import views

app_name = 'tecnic'

urlpatterns = [
    path('', views.intro, name='intro'),
    path('client/<int:id>', views.client, name='client'),
    path('change_status/<int:id>', views.change_status, name='change_status'),
    path('configuration', views.configuration, name='configuration'),
]

API/models.py
import hashlib
import base64
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.hashers import check_password

from rest_framework.authtoken.models import Token

def encrypt_password(password):
    password_bytes = password.encode('utf-8')
    sha256_result = hashlib.sha256(password_bytes)
    base64_hash = base64.b64encode(sha256_result.digest()).decode('utf-8')
    return base64_hash

# Create your models here.
class User(AbstractUser):
    phone = models.CharField(max_length=20)
    address = models.CharField(max_length=255, blank=True, null=True)
    work_status = models.CharField(max_length=255, default="Disponible")
    identity = models.CharField(max_length=20, null=True)
    is_blocked = models.BooleanField(default=False)

    def check_password(self, raw_password):
        return check_password(encrypt_password(raw_password), self.password)

class Comments(models.Model):
    comment = models.CharField(max_length=200, blank=False, null=False)
    date = models.DateField(blank=False, null=False)

class Stars(models.Model):
    star = models.IntegerField(blank=False, null=False)
    date = models.DateField(blank=False, null=False)

class Product(models.Model):
    name = models.CharField(max_length=20, blank=False, null=False)
    price = models.FloatField(blank=False, null=False)

class Problems(models.Model):
    title_description = models.CharField(max_length=30, blank=False, null=False)
    description = models.CharField(max_length=200, blank=False, null=False)
    status = models.CharField(max_length=20, default="Baja")

class Problems_Tikets(models.Model):
    description = models.CharField(max_length=200, blank=False, null=False)
    problem = models.ForeignKey(Problems, on_delete=models.CASCADE)
    user_with_problem = models.CharField(max_length= 50,blank=False, null=False)
    type_user = models.CharField(max_length=20, blank=False, null=False)
    photo = models.ImageField(upload_to='problems', blank=True, null=True)
    '''
    Usuarios con problemas pueden ser:
    - Tecnicos
    - Clientes
    - Call center
    - Manager
    '''

class Client(models.Model):
    products_bought = models.ManyToManyField(Product)
    username = models.CharField(max_length=20, blank=False, null=False)
    identity = models.CharField(max_length=20, blank=False, null=False)
    phone = models.CharField(max_length=20, blank=False, null=False)
    total_price = models.FloatField(blank=False, null=False)
    date_instalation = models.DateField(blank=True, null=True)
    part_of_day = models.CharField(max_length=20, blank=True, null=True)
    status_instalation = models.CharField(max_length=15, blank=True, null=True)
    is_accepted_by_manager = models.CharField(max_length=20, default="Esperando Aprobación")
    options_to_give_instalation = models.CharField(max_length=20, default="Recoger")
    photo_reciept = models.ImageField(upload_to='reciepts', blank=False, null=False)

    def photo_reciept_url(self):
        if self.photo_reciept:
            return self.photo_reciept.url
        return None
    
    def set_products_bought_ids(self, ids):
        self.products_bought.set(ids)
    
class Certificate(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    date_instalation = models.DateField(blank=False, null=False)
    firm = models.CharField(max_length=20, blank=False, null=False)
    photo = models.ImageField(upload_to='certificates', blank=False, null=False)

    def photo_url(self):
        if self.photo:
            return self.photo.url
        return None

class Tecnic(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    comments = models.ManyToManyField(Comments, blank=True)
    stars = models.ManyToManyField(Stars, blank=True)
    clients = models.ManyToManyField(Client, blank=True)
    certificates = models.ManyToManyField(Certificate, blank=True)
    location_lat = models.FloatField(blank=True, null=True)
    location_lon = models.FloatField(blank=True, null=True)
    city = models.CharField(max_length=50, blank=True, null=True)
    country = models.CharField(max_length=50, blank=True, null=True)
    business_name = models.CharField(max_length=50, blank=True, null=True)
    photo = models.ImageField(upload_to='tecnic', blank=True, null=True)
    token_phone = models.CharField(max_length=200, blank=True, null=True)
    token = models.OneToOneField(Token, on_delete=models.CASCADE, blank=True, null=True)

    def photo_url(self):
        if self.photo:
            return self.photo.url
        return None
    
class CallCenter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    '''
    Call center puede seleccionar el dia y la hora de la instalación del cliente
    Call center puede enviar el comprobante de pago del cliente
    Call center puede reasignar una fecha nueva de instalación del cliente

    '''
    photo = models.ImageField(upload_to='callcenter', blank=True, null=True)
    token_phone = models.CharField(max_length=200, blank=True, null=True)

    def photo_url(self):
        if self.photo:
            return self.photo.url
        return None
    
class Manger(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    tecnic = models.ManyToManyField(Tecnic, blank=True)
    clients = models.ManyToManyField(Client, blank=True)
    photo = models.ImageField(upload_to='manager', blank=True, null=True)
    token_phone = models.CharField(max_length=200, blank=True, null=True)

    def photo_url(self):
        if self.photo:
            return self.photo.url
        return None

tecnic/models.py
from django.db import models

# Create your models here.

tecnic/views.py
from django.shortcuts import get_object_or_404, render
from API.models import Tecnic, Client
import folium
from geopy.geocoders import Nominatim

# Create your views here.
def intro(request):
    return render(request, 'tecnic/intro.html',{
        'tecnic': Tecnic.objects.get(user=request.user)
    })

def client(request, id):
    return render(request, 'tecnic/client.html',{
        'tecnic': Tecnic.objects.get(user=request.user),
        'client': Client.objects.get(id=id)
    })

def change_status(request, id):
    client = get_object_or_404(Client, id=id)

    if request.method == 'POST':
        status = request.POST.get('status')
        client.status_instalation = status
        client.save()

    return render(request, 'tecnic/client.html', {
        'tecnic': Tecnic.objects.get(user=request.user),
        'client': client
    })

def configuration(request):
    tecnic = Tecnic.objects.get(user=request.user)
    geolocator = Nominatim(user_agent="mi_aplicacion")
    if request.method == 'POST':
        city = request.POST.get('city')
        country = request.POST.get('country')
        business_name = request.POST.get('business_name')

        location = geolocator.geocode(f"{business_name}, {city}, {country}")
        latitud = location.latitude
        longitud = location.longitude

        print(latitud, longitud)

        tecnic.location_lat = latitud
        tecnic.location_lon = longitud
        tecnic.business_name = business_name
        tecnic.city = city
        tecnic.country = country

        tecnic.save()

        mapa_final = folium.Map(location=[latitud, longitud], zoom_start=15)
        folium.Marker([latitud, longitud], popup=business_name).add_to(mapa_final)

        # Convertir el mapa a HTML
        mapa_html_final = mapa_final._repr_html_()

        return render(request, 'tecnic/configuration.html', {
            'tecnic': Tecnic.objects.get(user=request.user),
            'map': mapa_html_final
        })

    try:
        mapa_final = folium.Map(location=[str(tecnic.location_lat), str(tecnic.location_lon)], zoom_start=15)
        folium.Marker([tecnic.location_lat, tecnic.location_lon], popup="Tecnico").add_to(mapa_final)

        # Convertir el mapa a HTML
        mapa_html_final = mapa_final._repr_html_()
    except:
        return render(request, 'tecnic/configuration.html', {
            'tecnic': Tecnic.objects.get(user=request.user),
            'map': ''
        })
    return render(request, 'tecnic/configuration.html', {
        'tecnic': Tecnic.objects.get(user=request.user),
        'map': mapa_html_final
    })

tecnic/templates/tecnic/client.html
{% extends 'layout.html' %}
{% load static %}

{% block sidebar %}
<div class="select_item">
    <ul class="list_sidebar">
        <a href="{% url 'tecnic:intro' %}">
            <li class="item_sidebar">
                Inicio
            </li>
        </a>
        <a href="{% url 'tecnic:configuration' %}">
            <li class="item_sidebar">
                Configuración
            </li>
        </a>
        <a href="{% url 'startapp:ticket' 'tecnic' %}">
            <li class="item_sidebar">
                Ticket
            </li>
        </a>
        <li>Clientes</li>
        {% for client_id in  tecnic.clients.all %}
        <a href="{% url 'tecnic:client' client_id.id %}" {% if client_id.id == client.id %} style="color: blue; text-decoration: underline;" {% endif %}>
            <li class="item_sidebar">
                {{ client_id.username }} - {{ client_id.identity }}
            </li>
        </a>
        {% endfor %}
    </ul>
</div>
{% endblock %}

{% block content %}
<div class="container text-center body_form">
    <div class="row">
        <div class="col">
            <h3 class="principal_text">Crear Comprador</h3>
            <div class="container_create">
                <div class="input_info">
                    <label for="username">Nombre del comprador</label>
                    <input type="text" name="username" id="username" class="form-control" value="{{ client.username }}" readonly>
                </div>

                <div class="input_info">
                    <label for="identity">Cedula de identidad/RUC/Pasaporte</label>
                    <input type="number" name="identity" id="identity" class="form-control" value="{{ client.identity }}" readonly>
                </div>

                <div class="input_info">
                    <label for="phone">Celular</label>
                    <input type="number" name="phone" id="phone" class="form-control" value="{{ client.phone }}" readonly>
                </div>

                <div class="input_info">
                    <label>Productos a instalar</label>
                    <table class="table table-dark table-bordered caption-top">
                        <caption style="color: white;">Lista de productos</caption>
                        <thead>
                            <tr>
                                <th scope="col">Nombre</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for product in client.products_bought.all %}
                            <tr>
                                <td>{{ product.name }}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col">
            <h3 class="principal_text">Subir comprobante de pago</h3>
            <div class="container_create">
                <div class="input_info">
                    <label for="date_instalation">Fecha de instalación</label>
                    <input type="date" name="date_instalation" id="date_instalation" class="form-control" value="{{ client.date_instalation|date:'Y-m-d' }}" readonly>
                </div>                           
                <div class="input_info">
                    <label for="phone">Parte del día</label>
                    <select name="part_of_day" id="part_of_day" class="select_worker" disabled>
                        <option value="0">Seleccionar</option>
                        <option value="mañana" {% if client.part_of_day == 'mañana' %} selected {% endif %}>Mañana</option>
                        <option value="tarde" {% if client.part_of_day == 'tarde' %} selected {% endif %}>Tarde</option>
                    </select>
                </div>
                <div class="input_info">
                    <label for="options_to_give_instalation">Seleccione el tipo de entrega</label>
                    <select name="options_to_give_instalation" id="options_to_give_instalation" class="select_worker" disabled>
                        <option value="0">Seleccionar</option>
                        <option value="Recoger" {% if client.options_to_give_instalation == 'Recoger' %} selected {% endif %}>Recoger</option>
                        <option value="Delivery" {% if client.options_to_give_instalation == 'Delivery' %} selected {% endif %}>Delivery</option>
                    </select>
                </div>

                <div class="input_info">
                    <label for="status_instalation">Estatus de instalación</label>
                    <input type="text" name="status_instalation" id="status_instalation" class="form-control" value="{{ client.status_instalation}}" readonly>
                </div>

                <form id="changeStatusForm" method="post" action="{% url 'tecnic:change_status' client.id %}">
                    {% csrf_token %}
                    <input type="hidden" name="status" id="id_status">
                    <div class="container_create">
                        <div class="input_info">
                            <button type="button" class="btn btn-danger" onclick="changeStatus('Retrasado')">Cambiar estado a Retrasado</button>
                        </div>
                        {% if client.options_to_give_instalation == 'Recoger' %}
                        <div class="input_info">
                            <button type="button" class="btn btn-warning" onclick="changeStatus('Instalando')">Cambiar estado a Instalando</button>
                        </div>
                        {% else %}
                        <div class="input_info">
                            <button type="button" class="btn btn-warning" onclick="changeStatus('Viajando')">Cambiar estado a Viajando</button>
                        </div>
                        {% endif %}
                        <div class="input_info">
                            <button type="button" class="btn btn-success" onclick="changeStatus('Terminado')">Cambiar estado a Terminado</button>
                        </div>
                    </div>
                </form>

                {% if message %}
                <div class="alert alert-danger" role="alert">
                    {{ message }}
                </div>
                {% endif %}

                {% if success %}
                <div class="alert alert-success" role="alert">
                    {{ success }}: Nombre de usuario: {{ username }}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

<script>
    function changeStatus(status) {
        document.getElementById('id_status').value = status; // Agrega un campo oculto con el valor del estado
        document.getElementById('changeStatusForm').submit(); // Envía el formulario
    }
</script>
{% endblock %}

tecnic/templates/tecnic/configuration.html
{% extends 'layout.html' %}
{% load static %}

{% block sidebar %}
<div class="select_item">
    <ul class="list_sidebar">
        <a href="{% url 'tecnic:intro' %}">
            <li class="item_sidebar">
                Inicio
            </li>
        </a>
        <a href="{% url 'tecnic:configuration' %}">
            <li class="item_sidebar" style="color: blue; text-decoration: underline;">
                Configuración
            </li>
        </a>
        <a href="{% url 'startapp:ticket' 'tecnic' %}">
            <li class="item_sidebar">
                Ticket
            </li>
        </a>
        <li>Clientes</li>
        {% for client in  tecnic.clients.all %}
        <a href="{% url 'tecnic:client' client.id %}">
            <li class="item_sidebar">
                {{ client.username }} - {{ client.identity }}
            </li>
        </a>
        {% endfor %}
    </ul>
</div>
{% endblock %}

{% block content %}
<div class="container text-center body_form">
    <div class="row">
        <div class="col">
            <h3 class="principal_text">Seleccionar ubicación</h3>
            <div class="container_create">
                <form action="{% url 'tecnic:configuration' %}" method="post">
                    {% csrf_token %}
                    <div class="input_info">
                        <label for="business_name">Ingresa nombre del negocio</label>
                        <input type="text" name="business_name" id="business_name" placeholder="{{ tecnic.business_name }}" class="form-control">
                    </div>
                    <div class="input_info">
                        <label for="city">Ingresa la ciudad</label>
                        <input type="text" name="city" id="city" placeholder="{{ tecnic.city }}" class="form-control">
                    </div>
                    <div class="input_info">
                        <label for="country">Ingresa el pais</label>
                        <input type="text" name="country" id="country" placeholder="{{ tecnic.country }}" class="form-control">
                    </div>
                    <br>
                    <div class="input_info">
                        <button type="submit" class="btn btn-success">Cambiar ubicación</button>
                    </div>
                </form>             
            </div>
        </div>
        <div class="col">
            <h3 class="principal_text">Mapa</h3>
            <div class="container_create">
                <div class="map">
                    {{ map|safe }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

tecnic/templates/tecnic/intro.html
{% extends 'layout.html' %}
{% load static %}

{% block sidebar %}
<div class="select_item">
    <ul class="list_sidebar">
        <a href="{% url 'tecnic:intro' %}">
            <li class="item_sidebar" style="color: blue; text-decoration: underline;">
                Inicio
            </li>
        </a>
        <a href="{% url 'tecnic:configuration' %}">
            <li class="item_sidebar">
                Configuración
            </li>
        </a>
        <a href="{% url 'startapp:ticket' 'tecnic' %}">
            <li class="item_sidebar">
                Ticket
            </li>
        </a>
        <li>Clientes</li>
        {% for client in  tecnic.clients.all %}
        <a href="{% url 'tecnic:client' client.id %}">
            <li class="item_sidebar">
                {{ client.username }} - {{ client.identity }}
            </li>
        </a>
        {% endfor %}
    </ul>
</div>
{% endblock %}

{% block content %}
<div class="body_form">
    {% if messages %}
    <div class="alert alert-danger" role="alert">
        {{ messages }}
    </div>
    {% endif %}

    {% if success %}
    <div class="alert alert-success" role="alert">
        {{ success }}
    </div>
    {% endif %}

    <div class="search_information">
        <div class="box_finding">
            <label for="inpSearch1">Filtrar por cédula:</label><br>
            <input type="text" id="inpSearch1" name="inpSearch1" placeholder="Ingresar el código">
        </div>
        <div class="box_finding">
            <label for="inpSearch2">Filtrar por celular:</label><br>
            <input type="text" id="inpSearch2" name="inpSearch2" placeholder="Ingresar el código">
        </div>
    </div>
    <table class="table table-dark table-bordered caption-top" id="searchtable_callcenters">
        <caption style="color: white;">Lista de clientes</caption>
        <thead>
            <tr>
                <th scope="col">Usuario</th>
                <th scope="col">Cédula/RUC/Passaporte</th>
                <th scope="col">Celular</th>
                <th scope="col">Día de instalación</th>
                <th scope="col">Manaña/Tarde</th>
                <th scope="col">Estado de la instalación</th>
                <th scope="col">Productos Comprados</th>
                <th scope="col">Recoger/Delivery</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for client in tecnic.clients.all %}
            <tr class="searchable">
                <td>{{ client.username }}</td>
                <td>{{ client.identity }}</td>
                <td>{{ client.phone }}</td>
                <td>{{ client.date_instalation }}</td>
                <td>{{ client.part_of_day }}</td>
                <td>{{ client.status_instalation }}</td>
                <td>
                    {% for product in client.products_bought.all %}
                        {{ product.name }}<br>
                    {% endfor %}
                </td>
                <td>{{ client.options_to_give_instalation }}</td>
                <td class="actions-buttons">
                    <a href="{% url 'tecnic:client' client.id %}" class="btn btn-success">Cambiar estatus</a>
                    <form id="changeStatusForm" method="post" action="{% url 'tecnic:change_status' client.id %}">
                        {% csrf_token %}
                        <input type="hidden" name="status" value="Retrasado">
                        <button type="submit" class="btn btn-danger">Atrazar estatus</button>
                    </form>
                    <br>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}