API/urls.py
# Importaciones del programa
from . import views

# Django
from django.urls import path, include

# Rest Framework
from rest_framework import routers

router = routers.DefaultRouter()

router.register('comments', views.CommentsViewSet)
router.register('stars', views.StarsViewSet)
router.register('product', views.ProductViewSet)
router.register('problems', views.ProblemsViewSet)
router.register('problems_tikets', views.Problems_TiketsViewSet)
router.register('client', views.ClientViewSet)
router.register('certificate', views.CertificateViewSet)
router.register('tecnic', views.TecnicViewSet)
router.register('manager', views.ManagerViewSet)
router.register('callcenter', views.CallCenterViewSet)
router.register('user', views.UserViewSet)
router.register('notifications', views.PushNotificationAPIView, basename='notifications')

urlpatterns = [
    path('', include(router.urls)),
]

WorkSniffs/urls.py
from django.contrib import admin
from django.urls import path, include
from rest_framework.documentation import include_docs_urls

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),

    # Vistas normales
    path('', include("startapp.urls")),
    path('manager/', include("manager.urls")),
    path('callcenter/', include("callcenter.urls")),
    path('tecnic/', include("tecnic.urls")),
    path('user/', include("user.urls")),

    # API y documentación
    path('api/', include("API.urls")),
    path('docs/', include_docs_urls(title='WorkSniffs API', public=True)),
]

# Añadimos las rutas de los archivos multimedia
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

manager/urls.py
from django.urls import path
from . import views

app_name = "manager"

urlpatterns = [
    path("", views.principal_page, name="principal_page"),
    path("workers/", views.workers, name="workers"),
    path("delete_worker/<int:id>", views.delete_worker, name="delete_worker"),
    path("edit_worker/", views.edit_worker, name="edit_worker"),
    path("block_worker/<int:id>", views.block_worker, name="block_worker"),
    path("unblock_worker/<int:id>", views.unblock_worker, name="unblock_worker"),
    path("clients/", views.clients, name="clients"),
    path("accept_client/<int:id>", views.accept_client, name="accept_client"),
    path("reject_client/<int:id>", views.reject_client, name="reject_client"),
]

startapp/urls.py
from django.urls import path
from . import views

app_name = "startapp"

urlpatterns = [
    path("", views.login_view, name="login_view"),
    path("logout", views.logout_view, name="logout_view"),
    path("ticket/<str:type_user>/", views.ticket, name="ticket"),
]

manager/models.py
from django.db import models

# Create your models here.

manager/views.py
from django.shortcuts import render
from API.models import User, Tecnic, CallCenter, Manger, Client
from django.contrib.auth.hashers import make_password

# Create your views here.
import hashlib
import base64

def encrypt_password(password):
    password_bytes = password.encode('utf-8')
    sha256_result = hashlib.sha256(password_bytes)
    base64_hash = base64.b64encode(sha256_result.digest()).decode('utf-8')
    return base64_hash

def principal_page(request):
    if request.method == "POST":
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        phone = request.POST.get("phone")
        identity = request.POST.get("identity")
        password = request.POST.get("password")
        confirm = request.POST.get("confirm")
        worker_type = request.POST.get("worker_type")
        image = request.FILES.get("image")

        worker_type = int(worker_type)

        if worker_type == 0:
            return render(request, "index.html", {"message": "Seleccione un tipo de usuario"})
        
        if not image:
            return render(request, "index.html", {"message": "Suba una imagen"})

        # Crear username
        username = first_name + "_" + last_name

        # Verificar que el email no exista
        if User.objects.filter(email=email).exists():
            return render(request, "index.html", {"message": "El email ya existe"})
        
        # Verificar que el username no exista
        if User.objects.filter(username=username).exists():
            username = username + "_" + User.objects.last().id

        # Verificar que las contraseñas sean iguales
        if password != confirm:
            return render(request, "index.html", {"message": "Las contraseñas no coinciden"})
        
        # Verificar que la cedula no este repetida
        if User.objects.filter(identity=identity).exists():
            return render(request, "index.html", {"message": "La cedula ya existe"})
        
        # Verificar que el telefono no este repetido
        if User.objects.filter(phone=phone).exists():
            return render(request, "index.html", {"message": "El telefono ya existe"})
        
        # Encriptar la contraseña
        password = make_password(encrypt_password(password))

        # Crear el usuario
        user = User.objects.create(
            first_name=first_name,
            last_name=last_name,
            email=email,
            phone=phone,
            identity=identity,
            username=username,
            password=password
        )

        user.save()

        if worker_type == 1:
            callcenter = CallCenter.objects.create(
                user=user,
                photo = image
            )
            callcenter.save()
        elif worker_type == 2:
            tecnic = Tecnic.objects.create(
                user=user,
                photo = image
            )
            tecnic.save()
        else:
            manager = Manger.objects.create(
                user=user,
                photo = image
            )
            manager.save()

        return render(request, "index.html", {
            "success": "Usuario creado correctamente",
            "username": username
        })
    else:
        return render(request, "index.html", {})
    
def workers(request):
    callcenters = CallCenter.objects.all()
    tecnic = Tecnic.objects.all()
    return render(request, "workers/trabajadores.html", {
        "callcenters": callcenters,
        "tecnics": tecnic,
    })

def delete_worker(request, id):
    try:
        callcenter = CallCenter.objects.get(id=id)
    except:
        callcenter = None
    
    try:
        tecnic = Tecnic.objects.get(id=id)
    except:
        tecnic = None

    if callcenter is None and tecnic is None:
        return render(request, "workers/trabajadores.html", {
            "callcenter": callcenter,
            "tecnic": tecnic,
            "message": "No se encontro el trabajador"
        })
    
    if callcenter is not None:
        User.objects.get(id=callcenter.user.id).delete()
    else:
        User.objects.get(id=tecnic.user.id).delete()

    return render(request, "workers/trabajadores.html", {
        "callcenter": callcenter,
        "tecnic": tecnic,
    })

def edit_worker(request):
    if request.method == "POST":
        id = request.POST.get("id")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        identity = request.POST.get("identity")
        phone = request.POST.get("phone")
        status = request.POST.get("status")

        try:
            user = User.objects.get(id=id)

            username = first_name + "_" + last_name

            user.first_name = first_name
            user.last_name = last_name
            user.username = username
            user.email = email
            user.identity = identity
            user.phone = phone
            user.work_status = status

            user.save()

            callcenters = CallCenter.objects.all()
            tecnic = Tecnic.objects.all()
            return render(request, "workers/trabajadores.html", {
                "success": "Usuario actualizado correctamente",
                "callcenters": callcenters,
                "tecnics": tecnic
            })
        except:
            return render(request, "workers/trabajadores.html", {
                "message": "No se encontro el trabajador"
            })

def block_worker(request, id):
    try:
        user = User.objects.get(id=id)
        user.is_blocked = True
        user.save()

        callcenters = CallCenter.objects.all()
        tecnic = Tecnic.objects.all()
        return render(request, "workers/trabajadores.html", {
            "success": "Usuario bloqueado correctamente",
            "callcenters": callcenters,
            "tecnics": tecnic
        })
    except:
        return render(request, "workers/trabajadores.html", {
            "message": "No se encontro el trabajador",
            'callcenters': callcenters,
            'tecnics': tecnic
        })
    
def unblock_worker(request, id):
    try:
        user = User.objects.get(id=id)
        user.is_blocked = False
        user.save()

        callcenters = CallCenter.objects.all()
        tecnic = Tecnic.objects.all()
        return render(request, "workers/trabajadores.html", {
            "success": "Usuario desbloqueado correctamente",
            "callcenters": callcenters,
            "tecnics": tecnic
        })
    except:
        return render(request, "workers/trabajadores.html", {
            "message": "No se encontro el trabajador",
            "callcenters": callcenters,
            "tecnics": tecnic
        })
    
def clients(request):
    clients = Client.objects.all()
    return render(request, "clients/clients.html", {
        'clients': clients
    })

def accept_client(request, id):
    try:
        client = Client.objects.get(id=id)
        client.is_accepted_by_manager = "Aceptado"
        client.save()

        clients = Client.objects.all()

        # Sacar un tecnico que no tenga clientes
        try:
            tecnic = Tecnic.objects.filter(clients=None).first()
            tecnic.clients.add(client)
            tecnic.save()
        except:
            pass

        # Si no encuentra tecnico, encontrar el que menos clientes tenga
        if tecnic is None:
            tecnic = Tecnic.objects.all()
            tecnic = sorted(tecnic, key=lambda x: x.clients.count())
            tecnic = tecnic[0]
            tecnic.clients.add(client)
            tecnic.save()

        return render(request, "clients/clients.html", {
            "success": "Cliente aceptado correctamente",
            "clients": clients
        })
    except:
        return render(request, "clients/clients.html", {
            "message": "No se encontro el cliente",
            "clients": clients
        })
    
def reject_client(request, id):
    try:
        client = Client.objects.get(id=id)
        client.is_accepted_by_manager = "Rechazado"
        client.save()

        clients = Client.objects.all()
        return render(request, "clients/clients.html", {
            "success": "Cliente rechazado correctamente",
            "clients": clients
        })
    except:
        return render(request, "clients/clients.html", {
            "message": "No se encontro el cliente",
            "clients": clients
        })

manager/templates/workers/trabajadores.html
{% extends 'layout.html' %}
{% load static %}

{% block sidebar %}
<div class="select_item">
    <ul class="list_sidebar">
        <a href="{% url 'manager:principal_page' %}">
            <li class="item_sidebar">
                Inicio
            </li>
        </a>
        <a href="{% url 'manager:workers' %}" style="color: blue; text-decoration: underline;">
            <li class="item_sidebar">
                Trabajadores
            </li>
        </a>
        <a href="{% url 'manager:clients' %}">
            <li class="item_sidebar">
                Clientes
            </li>
        </a>
    </ul>
    <div class="ticket_sidebar">
        <a href="{% url 'startapp:ticket' 'manager' %}">
            Ticket
        </a>
    </div>
</div>
{% endblock %}

{% block content %}
<div class="body_form">
    {% if messages %}
    <div class="alert alert-danger" role="alert">
        {{ messages }}
    </div>
    {% endif %}

    {% if success %}
    <div class="alert alert-success" role="alert">
        {{ success }}
    </div>
    {% endif %}
    <div class="search_information">
        <div class="box_finding">
            <label for="inpSearch5">Filtrar por cédula:</label><br>
            <input type="text" id="inpSearch5" name="inpSearch5" placeholder="Ingresar el código">
        </div>
    </div>
    <table class="table table-dark table-bordered caption-top" id="searchtable_callcenters">
        <caption style="color: white;">Lista de callcenter</caption>
        <thead>
            <tr>
                <th scope="col">Nombre/s</th>
                <th scope="col">Apellido/s</th>
                <th scope="col">Usuario</th>
                <th scope="col">Email</th>
                <th scope="col">Telefono</th>
                <th scope="col">Cedula/RUC/Pasaporte</th>
                <th scope="col">Esta bloqueado</th>
                <th scope="col">Estatus del trabajador</th>
                <th scope="col">Foto</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for callcenter in callcenters %}
            <tr class="searchable">
                <td>{{ callcenter.user.first_name }}</td>
                <td>{{ callcenter.user.last_name }}</td>
                <td>{{ callcenter.user.username }}</td>
                <td>{{ callcenter.user.email }}</td>
                <td>{{ callcenter.user.phone }}</td>
                <td>{{ callcenter.user.identity }}</td>
                {% if callcenter.user.is_blocked %}
                <td>Si</td>
                {% else %}
                <td>No</td>
                {% endif %}
                <td>{{ callcenter.user.work_status }}</td>
                <td><img src="{{ callcenter.photo.url }}" alt="Foto" width="100" height="100"></td>
                <td class="actions-buttons">
                    <button class="btn btn-info" onclick="editWorker('{{ callcenter.user.id }}')">Editar</button>
                    <a href="{% url 'manager:delete_worker' callcenter.id %}" class="btn btn-danger">Eliminar</a>
                    {% if not callcenter.user.is_blocked %}
                    <a href="{% url 'manager:block_worker' callcenter.user.id %}" class="btn btn-warning">Bloquear</a>
                    {% else %}
                    <a href="{% url 'manager:unblock_worker' callcenter.user.id %}" class="btn btn-warning">Desbloquear</a>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <table class="table table-dark table-bordered caption-top" id="searchtable_tecnics">
        <caption style="color: white;">Lista de tecnicos</caption>
        <thead>
            <tr>
                <th scope="col">Nombre/s</th>
                <th scope="col">Apellido/s</th>
                <th scope="col">Usuario</th>
                <th scope="col">Email</th>
                <th scope="col">Teléfono</th>
                <th scope="col">Cédula/RUC/Pasaporte</th>
                <th scope="col">Esta bloqueado</th>
                <th scope="col">Estatus del trabajador</th>
                <th scope="col">Clientes</th>
                <th scope="col">Foto</th>
                <th scope="col">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for tecnic in tecnics %}
            <tr class="searchable">
                <td>{{ tecnic.user.first_name }}</td>
                <td>{{ tecnic.user.last_name }}</td>
                <td>{{ tecnic.user.username }}</td>
                <td>{{ tecnic.user.email }}</td>
                <td>{{ tecnic.user.phone }}</td>
                <td>{{ tecnic.user.identity }}</td>
                {% if tecnic.user.is_blocked %}
                <td>Si</td>
                {% else %}
                <td>No</td>
                {% endif %}
                <td>{{ tecnic.user.work_status }}</td>
                <td>
                    {% for client in tecnic.clients.all %}
                        {{ client.username }}<br>
                    {% endfor %}
                </td>
                <td><img src="{{ tecnic.photo.url }}" alt="Foto" width="100" height="100"></td>
                <td class="actions-buttons">
                    <button class="btn btn-info" onclick="editWorker('{{ tecnic.user.id }}')">Editar</button>
                    <a href="{% url 'manager:delete_worker' tecnic.id %}" class="btn btn-danger">Eliminar</a>
                    <a href="{% url 'manager:block_worker' tecnic.user.id %}" class="btn btn-warning">Bloquear</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

<form action="{% url 'manager:edit_worker' %}" method="post">
    {% csrf_token %}
    <div class="background" id="background">
        <div class="edit_container" id="edit_container">
            
        </div>
    </div>
</form>
{% endblock %}